// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Practica4ParcialUYS.SitioCine {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiCineSoap", Namespace="http://tempuri.org/")]
    public partial class ServiCine : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarPeliOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarPeliOperationCompleted;
        
        /// CodeRemarks
        public ServiCine() {
            this.Url = "http://192.168.1.96:8080/ServiCine.asmx";
        }
        
        public ServiCine(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event BuscarPeliCompletedEventHandler BuscarPeliCompleted;
        
        /// CodeRemarks
        public event GuardarPeliCompletedEventHandler GuardarPeliCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarPeli", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarPeli(string Nombre) {
            object[] results = this.Invoke("BuscarPeli", new object[] {
                        Nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// CodeRemarks
        public void BuscarPeliAsync(string Nombre) {
            this.BuscarPeliAsync(Nombre, null);
        }
        
        /// CodeRemarks
        public void BuscarPeliAsync(string Nombre, object userState) {
            if ((this.BuscarPeliOperationCompleted == null)) {
                this.BuscarPeliOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarPeliOperationCompleted);
            }
            this.InvokeAsync("BuscarPeli", new object[] {
                        Nombre}, this.BuscarPeliOperationCompleted, userState);
        }
        
        private void OnBuscarPeliOperationCompleted(object arg) {
            if ((this.BuscarPeliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarPeliCompleted(this, new BuscarPeliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarPeli", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarPeli(string Nombre, string Genero, string Clasificacion, string Duracion, string Director, string Actores, string Sinopsis, string Fecha) {
            object[] results = this.Invoke("GuardarPeli", new object[] {
                        Nombre,
                        Genero,
                        Clasificacion,
                        Duracion,
                        Director,
                        Actores,
                        Sinopsis,
                        Fecha});
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public void GuardarPeliAsync(string Nombre, string Genero, string Clasificacion, string Duracion, string Director, string Actores, string Sinopsis, string Fecha) {
            this.GuardarPeliAsync(Nombre, Genero, Clasificacion, Duracion, Director, Actores, Sinopsis, Fecha, null);
        }
        
        /// CodeRemarks
        public void GuardarPeliAsync(string Nombre, string Genero, string Clasificacion, string Duracion, string Director, string Actores, string Sinopsis, string Fecha, object userState) {
            if ((this.GuardarPeliOperationCompleted == null)) {
                this.GuardarPeliOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarPeliOperationCompleted);
            }
            this.InvokeAsync("GuardarPeli", new object[] {
                        Nombre,
                        Genero,
                        Clasificacion,
                        Duracion,
                        Director,
                        Actores,
                        Sinopsis,
                        Fecha}, this.GuardarPeliOperationCompleted, userState);
        }
        
        private void OnGuardarPeliOperationCompleted(object arg) {
            if ((this.GuardarPeliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarPeliCompleted(this, new GuardarPeliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void BuscarPeliCompletedEventHandler(object sender, BuscarPeliCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarPeliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarPeliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GuardarPeliCompletedEventHandler(object sender, GuardarPeliCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarPeliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarPeliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
